### ISSUE TITLE
Make the work app optional

### ISSUE THREAD

**Issue by bhaugen** [gopacifia/DEEP#3]
The easy part is to include in settings.INSTALLED_APPS or not. If not, it won't be available.

The other part is to find and guard all references (which might just be in /valuenetwork/valuenetwork/templates/_account_bar.html) if the work app is not installed.

**Comment by fosterlynn** [comment]
>The other part is to find and guard all references (which might just be in /valuenetwork/valuenetwork/templates/_account_bar.html) if the work app is not installed.

Yes I think this is the only place.

However, I think the work app is where GP wants to go.  It is limited now because Freedom Coop is in the middle of creating it.

The work app includes:
* membership requests and comments
* profile creation, putting self on the map
* segregation of projects / groups from each other based on agent associations

The work app will also be where we add the ability to create resource types, exchange types, and process patterns by project / group. GP will need that.

Eventually I think the work app will contain everything needed by groups or individuals who are part of the network, and the main app ("admin app" which is the same as the older "Sensorica app" right now) will be for a small circle of admins.

**Comment by numapanuma** [comment]
I agree with Lynn, the structure of our network is similar to FreedomCoop's as context agents might choose to open their process and tasks or keep them private to some extent. So the work app is needed.

**Comment by bhaugen** [comment]
OK, so should we close this issue?
